### ISSUE TITLE
Did Smart EQ Connect just break?

### ISSUE THREAD

**Issue by Ocramius** [ReneNulschDE/ha-smart-eq-connect#4]
Seen #3 and #2 meanwhile.

My HA stopped updating Smart EQ Connect data recently: my suspicion is that Mercedes is "fucking around" (technical terminology) on their end, while they released their new car.

Relevant errors: 

```
Logger: homeassistant
Source: custom_components/smarteqconnect/api.py:68
integration: Smart EQ Connect (documentation, issues)
First occurred: 08:01:27 (1 occurrences)
Last logged: 08:01:27
Error doing job: Task exception was never retrieved

Traceback (most recent call last):
  File "/config/custom_components/smarteqconnect/__init__.py", line 157, in update_all
    await self.client.update()
  File "/config/custom_components/smarteqconnect/client.py", line 79, in update
    car_detail = await self.api.get_car_details(car.finorvin)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smarteqconnect/api.py", line 88, in get_car_details
    return await self._request("get", f"/seqc/v0/vehicles/{ vin }/refresh-data?requestedData=BOTH")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/smarteqconnect/api.py", line 68, in _request
    async with session.request(method, url, proxy=SYSTEM_PROXY, verify_ssl=VERIFY_SSL, **kwargs) as resp:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1194, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 504, in _request
    with timer:
  File "/usr/local/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

```

Relevant warnings:

```
Logger: homeassistant.const
Source: helpers/deprecation.py:205
First occurred: March 23, 2024 at 03:48:19 (3 occurrences)
Last logged: March 23, 2024 at 03:48:19

    LENGTH_KILOMETERS was used from smarteqconnect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.KILOMETERS instead, please create a bug report at https://github.com/ReneNulschDE/ha-smart-eq-connect/issues
    LENGTH_MILES was used from smarteqconnect, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfLength.MILES instead, please create a bug report at https://github.com/ReneNulschDE/ha-smart-eq-connect/issues
```

On this end, I'm mostly trying to find information about this first, especially for future readers to find the same error messages and have pointers :-) 

Their EQ Connect app also breaks spectacularly (android app just crashes when trying to look at car data), so it's not necessarily this component's fault compatibility either.

Should I just try configuring https://github.com/ReneNulschDE/mbapi2020 and attempt switching to [MercedesME](https://www.mbusa.com/en/mercedes-me-connect)?

**Comment by ReneNulschDE** [comment]
I do not maintain this repo anymore. Please try to use the mbapi2020 component. Most of the users switched already to this component.

**Comment by Ocramius** [comment]
Thanks, that's the info I was missing :-) 

May I suggest just adding that as a notice to `README.md`? Maybe archiving the repo, perhaps? Mostly to avoid wrong signaling :D

**Comment by ReneNulschDE** [comment]
Done, Thx for the hint.
